language: cpp

compiler:
  - gcc

os:
  - linux

addons:
  apt:
    packages:
      - doxygen
      - graphviz
      - python3
      - python3-setuptools
      - python3-pip

install:
  - pip3 install gcovr
  - pip3 install -r docs/requirements.txt
  - wget https://github.com/Kitware/CMake/releases/download/v3.16.4/cmake-3.16.4-Linux-x86_64.sh
  - chmod +x cmake-3.16.4-Linux-x86_64.sh
  - mkdir cmake_bin
  - ./cmake-3.16.4-Linux-x86_64.sh --skip-license --prefix=cmake_bin
  - export PATH="$(pwd)/cmake_bin/bin:$PATH"
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_EXAMPLES=ON -DBUILD_DOCUMENTATION=ON -DBUILD_TESTING=ON ..

jobs:
  include:
    - stage: compile-test-doc
      script:
        - make main
        - make coverage
        - bash <(curl -s https://codecov.io/bash)
        - make sphinx
