name: cookiecutter-tests

on: [push]

jobs:
  cookiecutter-compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install gcc-9 g++-9
          sudo ln -f /usr/bin/gcov-9 /usr/bin/gcov
          pip install gcovr cookiecutter
        
      - name: Run Cookiecutter
        run: |
          cookiecutter --no-input https://github.com/kiwi-lang/cxx_seed

      - name: compile
        run: |
          cd test_project
          git submodule update --init
          mkdir build
          cd build
          GCOV=gcov-9 CC=gcc-9 CXX=g++-9 cmake ..
          make enable-debug
          make enable-test
          make -j 4
          make coverage
          bash <(curl -s https://codecov.io/bash)
